[tool]
id = "com.kezo.tide"
label = "Tide"
versionCode = 32
versionName = "2.1"
permissions = ["android.permission.INTERNET"]
# use "com.thelightphone.sdk.emulator" when running on the LightOS emulator
serverPackage = "com.lightos"
